name: CI

# Run on push only on ci
# Otherwise it may trigger concurrently `push & pull_request` on PRs.
on:
  push:
    branches:
      - ci
    paths-ignore:
      - '*.md'
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
      - 'tools/**'
      - 'graphs/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'LICENSE'
      - 'tools/**'
      - 'graphs/**'
  workflow_dispatch:

jobs:
  #
  # Continuos Integration
  #
  integration:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Get branch name
        id: branch
        run: echo ::set-output name=current_branch::${GITHUB_REF#refs/*/}

      - name: Prisma generate
        run: yarn prisma:generate

      - name: Run linter
        run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn lint:ci

      - name: Run builder
        run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn build:ci

      # - name: Run tester
      #   run: NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn test:ci

      # - name: Combine coverage
      #   run: |
      #     NX_BRANCH=${{ steps.vars.outputs.current_branch }} yarn coverage:merge

      # - name: Push coverage to coveralls
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path-to-lcov: './coverage/lcov.combo.info'
